---
title: "dasper-vignette"
output: 
  html_document:
    code_folding: show
    theme: spacelab
    highlight: kate
    df_print: paged
    toc: true
    toc_float: true
    number_sections: true
vignette: >
  %\VignetteIndexEntry{dasper-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(dasper)
devtools::load_all("/home/dzhang/packages/dasper/")
```

# Merge junctions

```{r}

juncs <-
  merge_junc(junc_paths = c("../data-raw/example_juncs_1.txt",
                            "../data-raw/example_juncs_2.txt"),
             sample_ids = c("eg1", "eg2"),
             load_func = .load_STAR,
             chr_to_filter = c(1:22, "X", "Y", "M"))

juncs[["metadata"]]

juncs[["raw_count"]]

```

# Annotate junctions using reference annotation 

```{r}

load("../data/example_juncs.rda")
load("../tests/testthat/example_gtf.rda")

juncs[["metadata"]] <- 
  annotate_junc_ref(junc_metadata = juncs[["metadata"]], 
                    gtf = ref)

juncs[["metadata"]]

```

# Filter junctions

```{r}

blacklist_gr <- rtracklayer::import("/data/references/ENCODE_blacklist_v2/hg38-blacklist.v2.bed", format = "bed")
GenomeInfoDb::seqlevels(blacklist_gr) <- GenomeInfoDb::seqlevels(blacklist_gr) %>% stringr::str_replace("chr", "")

juncs <- 
  filter_junc(junc_metadata = juncs[["metadata"]], 
              raw_count = juncs[["raw_count"]], 
              count_thresh = 5, 
              n_samp = 1, 
              size = c(20, 1e6), 
              junc_cats = c("ambig_gene", "none"), 
              blacklist_gr = blacklist_gr)

```




